name: "Adiciona comentário a issue ou pull request"
description: "Essa action inclui comentário em issues ou PRs"
author: "JvictorMarques"
inputs:
  GITHUB_TOKEN:
    description: "Token de autenticação do GitHub"
    required: true
  issueId:
    description: "ID da issue ou pull request"
    required: true
  comment:
    description: "Comentário a ser adicionado"
    required: true
outputs:
  comment-id:
    description: "ID do comentário adicionado"
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "message-square"
  color: "blue"